server:
  port: 8088
  address: 0.0.0.0  # ← Важно! Разрешает подключения со всех интерфейсов

spring:
  application:
    name: TicTacToe Server

logging:
  level:
    org.springframework.web: DEBUG
    org.web.controller: DEBUG